### 1. 인공지능을 학습할 때 알아야 할 주요 모델과 기술

인공지능은 가장 넓은 개념으로 이를 구현하는 방법 중에 데이터를 기반으로 학습하는 머신러닝이 있다. 또한, 인공신경망의 한 종류인 딥러닝은 머신러닝의 방법 중 하나로 다음 그림과 같이 나타낼 수 있다.

<img src="https://hackernoon.imgix.net/images/9ln3ztv.jpg" height="300px" width="500px">

과거의 전통적인 프로그래밍은 데이터와 규칙을 통해 기계로부터 결과를 출력했다면, 머신러닝은 데이터와 정답 쌍을 기계에 학습시켜 스스로 규칙을 발견하도록 하는 기술이다. 이때, 목표는 training data를 완벽하게 학습하여 재현하는 것이 아니라, 새로운 데이터에 대해 task를 잘 수행할 수 있도록 통계적 모형을 구축하는 것이다.

머신러닝의 종류는 크게 다음과 같이 구분할 수 있다.

- 지도 학습(Supervised Learning)
  - Training data에 label이 있는 경우
  - ex) 회귀분석, 로지스틱 회귀분석, 의사결정나무, 랜덤포레스트, 서포트 벡터 머신 등
- 비지도 학습(Unsupervised Learning)
  -  Training data에 label이 없는 경우
  - ex) 주성분 분석, 계층 클러스터링, K-평균 클러스터링 등
- 준지도 학습(Semi-supervised Learning)
  - 일부 training data에 label이 있는 경우
- 강화학습(Reinforcement Learning)
  - 고정된 데이터셋이 아닌 특정 환경이 주어진 경우
  - 행동(Action)에 대한 보상(Reward)으로 학습이 이루어진다 

머신러닝의 모형 및 주요 기술에는 시계열 분석(추세 분석, 미래 수요 예측, 자동 문장 생성 등), OCR(이미지 속 텍스트 추출), 이미지 분류, 추천, 영상 처리, 자연어 처리, 챗봇, 음성 인식 등 그 종류가 다양하다. 

### 2. 머신러닝의 지도학습의 대표적인 모델과 기술

$(𝒙^1, 𝑦^1) , … , (𝒙^𝑁, 𝑦^𝑁)$의 레이블링 된 샘플이 있을 때, 매핑 함수 $𝑔: 𝑿 → 𝒀$를 학습해서 새로운 $𝒙'$가 주어질 때 적합한 $𝑦'$를 예측하여 출력하는 것을 지도학습(Supervised Learning)이라고 한다. 이때, 지도학습 알고리즘의 output $y$가 continuous 또는 discrete함에 따라 회귀(Regression)와 분류(Classification) 크게 두가지 유형으로 구분할 수 있다.

<img src="https://www.simplilearn.com/ice9/free_resources_article_thumb/Regression_vs_Classification.jpg" height="250px" width="400px">

지도학습의 대표적인 모델은 다음과 같다.

- 선형 회귀분석(Linear Regression): 종속 변수와 하나 이상의 독립 변수 간의 관계를 설명하는 선형식을 찾는 모델이다. 이때, 독립 변수의 개수가 하나일 때를 단순 선형 회귀, 여러개인 경우에 다중 선형 회귀라고 한다.

  <img src="https://media.geeksforgeeks.org/wp-content/uploads/20231129130431/11111111.png" height="200px" width="300px">

- 로지스틱 회귀분석(Logistic Regression): 선형 회귀분석은 출력변수가 연속적인 값에만 가능한 반면, 로지스틱 회귀분석은 범주형도 가능하다.

  <img src="https://www.researchgate.net/publication/367007823/figure/fig1/AS:11431281112303217@1673379396543/Logistic-regression-of-binary-classification-353-Support-Vector-Machine-SVM.ppm" height="240px" width="300px">

- K-최근접 이웃(KNN, K-nearest Neighbors): 기본적으로 유클리디안 거리를 통해 K개의 데이터 포인트 중 가장 가까이 있는 포인트의 라벨에 분류하는 모델

  <img src="https://miro.medium.com/v2/resize:fit:505/0*2_qzcm2gSe9l67aI.png" height="250px" width="300px">
  
- 결정 트리(Decision Tree Classification): 특정 기준에 따라 데이터를 구분해서 일련의 분류 규칙을 수행하는 모델이다.

  <img src="https://www.mastersindatascience.org/wp-content/uploads/sites/54/2022/05/tree-graphic.jpg" height="200px" width="300px">

- 랜덤 포레스트(Random Forest Classification): 여러 개의 의사결정나무를 구성하고, 각 의사결정나무의 예측 결과를 다수결 방식으로 조합하여 최종 예측 결과를 결정하는 모델이다.

  <img src="https://miro.medium.com/v2/resize:fit:1010/1*R3oJiyaQwyLUyLZL-scDpw.png" height="200px" width="300px">

- 서포트 벡터 머신(SVM, Support Vector Machine): 서포트 벡터(경계선) 간의 너비를 최대화, 오차를 최소화하는 것을 목표로 하며, 고차원 데이터셋을 분류하는데 좋은 성능을 보인다.

  <img src="https://3.bp.blogspot.com/-12I3KUZYAZU/WHI90_mZokI/AAAAAAAAFzg/qaaiCYvhwT41_rp0PEQjE7GFkPEtNrzkwCLcB/s1600-rw/SVM%2Bin%2BR.png" height="200px" width="300px">

- 나이브 베이즈(Naive Bayes Classifier): Feature끼리 조건부 독립이라는 가정하에 분류가 이루어지며, 설명하기 쉽다는 장점이 있다.

### 3. Scikit-learn 분류 또는 회귀 알고리즘 실습

In [2]:
import pandas as pd
from sklearn.datasets import load_wine

# dataset -> dataframe
wine = load_wine()
print(wine.DESCR) # the full description of the dataset

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            10.6  30.0    19.5   3.3
    Ma

In [3]:
for i in range(0, len(wine.data)):
  print(i+1, wine.data[i], wine.target[i]) # sample -> [feature vector], label

1 [1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
 2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03] 0
2 [1.32e+01 1.78e+00 2.14e+00 1.12e+01 1.00e+02 2.65e+00 2.76e+00 2.60e-01
 1.28e+00 4.38e+00 1.05e+00 3.40e+00 1.05e+03] 0
3 [1.316e+01 2.360e+00 2.670e+00 1.860e+01 1.010e+02 2.800e+00 3.240e+00
 3.000e-01 2.810e+00 5.680e+00 1.030e+00 3.170e+00 1.185e+03] 0
4 [1.437e+01 1.950e+00 2.500e+00 1.680e+01 1.130e+02 3.850e+00 3.490e+00
 2.400e-01 2.180e+00 7.800e+00 8.600e-01 3.450e+00 1.480e+03] 0
5 [1.324e+01 2.590e+00 2.870e+00 2.100e+01 1.180e+02 2.800e+00 2.690e+00
 3.900e-01 1.820e+00 4.320e+00 1.040e+00 2.930e+00 7.350e+02] 0
6 [1.42e+01 1.76e+00 2.45e+00 1.52e+01 1.12e+02 3.27e+00 3.39e+00 3.40e-01
 1.97e+00 6.75e+00 1.05e+00 2.85e+00 1.45e+03] 0
7 [1.439e+01 1.870e+00 2.450e+00 1.460e+01 9.600e+01 2.500e+00 2.520e+00
 3.000e-01 1.980e+00 5.250e+00 1.020e+00 3.580e+00 1.290e+03] 0
8 [1.406e+01 2.150e+00 2.610e+00 1.760e+01 1.210e+02 2.600e+00 2.51

In [4]:
df = pd.DataFrame(wine.data, columns=wine.feature_names) # feature
df['class'] = wine.target # target
df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  class  
0                            3.92   1065.0      0  
1                            3.40   1050.0      0  
2                            3.17   1185.0      0  
3                            3.45   1480.0      0  
4                            2.93    735.0      0  
..                            ...      ...    ...  
173                          1.74    740.0      2  
174                          1.56    750.0      2  
175                          1.56    835.0      2  
176                          1.62    840.0      2  
177                          1.60    560.0      2  

[178 rows x 14 columns]

In [5]:
df.columns

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline', 'class'],
      dtype='object')

In [6]:
X = df[wine.feature_names]
y = df['class'] # label

In [7]:
# train/test data
from sklearn.model_selection import train_test_split
X_tn, X_te, y_tn, y_te = train_test_split(X, y, random_state=0)

In [8]:
# standardization
from sklearn.preprocessing import StandardScaler
std_scale = StandardScaler()
std_scale.fit(X_tn)
X_tn_std = std_scale.transform(X_tn)
X_te_std = std_scale.transform(X_te)

In [9]:
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# Support Vector Machine
clf_svm = svm.SVC(kernel='linear')
clf_svm.fit(X_tn_std, y_tn) # train

pred_svm = clf_svm.predict(X_te_std) # task

conf_matrix = confusion_matrix(y_te, pred_svm)
print(conf_matrix)

class_report = classification_report(y_te, pred_svm)
print(class_report)

[[16  0  0]
 [ 0 21  0]
 [ 0  0  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        21
           2       1.00      1.00      1.00         8

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [31]:
import numpy as np

# Support Vector Machine
clf_svm = svm.SVC(gamma=0.1, C=10)
clf_svm.fit(X_tn_std, y_tn)

pred_svm = clf_svm.predict(X_te_std)

conf_matrix = confusion_matrix(y_te, pred_svm)
print(conf_matrix)

# confusion matrix 직접 구현 연습
conf_practice = np.zeros((3, 3))
for i in range(len(pred_svm)):
  conf_practice[pred_svm[i]][y_te.tolist()[i]] += 1
print(conf_practice)

wrong = 0
for i in range(3):
  wrong += conf_practice[i][i]
accuracy = wrong / len(pred_svm)
print("The accuracy of test set is:", accuracy*100, "%.")


class_report = classification_report(y_te, pred_svm)
print(class_report)

[[16  0  0]
 [ 0 21  0]
 [ 0  0  8]]
[[16.  0.  0.]
 [ 0. 21.  0.]
 [ 0.  0.  8.]]
The accuracy of test set is: 100.0 %.
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        21
           2       1.00      1.00      1.00         8

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [41]:
from sklearn.model_selection import cross_val_score
from sklearn import datasets

wine = datasets.load_wine()
S = svm.SVC(gamma=0.001)
accuracies = cross_val_score(S, wine.data, wine.target, cv=5) # 5-fold

print(accuracies)
print("accuracy(avg)=%0.3f, standard deviation=%0.3f" %(accuracies.mean()*100, accuracies.std()))

[0.66666667 0.63888889 0.63888889 0.65714286 0.8       ]
accuracy(avg)=68.032, standard deviation=0.061


In [ ]:
# Logistic Regression

clf_lr = LogisticRegression()
clf_lr.fit(X_tn_std, y_tn)

pred_lr = clf_lr.predict(X_te_std)

conf_matrix = confusion_matrix(y_te, pred_lr)
print(conf_matrix)

class_report = classification_report(y_te, pred_lr)
print(class_report)

[[16  0  0]
 [ 0 21  0]
 [ 0  0  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        21
           2       1.00      1.00      1.00         8

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [ ]:
# Gaussian Naive Bayes

clf_gnb = GaussianNB()
clf_gnb.fit(X_tn_std, y_tn)

pred_gnb = clf_gnb.predict(X_te_std)

conf_matrix = confusion_matrix(y_te, pred_gnb)
print(conf_matrix)

class_report = classification_report(y_te, pred_gnb)
print(class_report)

[[16  0  0]
 [ 2 18  1]
 [ 0  0  8]]
              precision    recall  f1-score   support

           0       0.89      1.00      0.94        16
           1       1.00      0.86      0.92        21
           2       0.89      1.00      0.94         8

    accuracy                           0.93        45
   macro avg       0.93      0.95      0.94        45
weighted avg       0.94      0.93      0.93        45

